[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.74.3"

[[headers]]
  for = "/*"

[headers.values]
  X-Frame-Options = "SAMEORIGIN"
  X-Content-Type-Options = "nosniff"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/favicon.ico"

[headers.values]
  Content-Type = "image/x-icon"

[[headers]]
  for = "/*.js"

[headers.values]
  Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "/*.webmanifest"

[headers.values]
  Content-Type = "application/manifest+json; charset=utf-8"

[[headers]]
  for = "/*.json"

[headers.values]
  Content-Type = "application/json; charset=utf-8"

